### ISSUE TITLE
Lack of `read-writeonce` support?

### ISSUE THREAD

**Issue by plaes** [embassy-rs/chiptool#38]
When trying with updated set of SVD's ([taken from nrfx](https://github.com/NordicSemiconductor/nrfx/tree/master/mdk) I ended up with following traceback:

```
Error: In device `nrf52`

Caused by:
    0: In peripheral `APPROTECT`
    1: In register `FORCEPROTECT`
    2: Parsing unknown access at 1010:11
    3: unknown access variant 'read-writeonce' found
```

And there's also issue with outdated SVD's, at least SVD for nrf52832 seems to originate from between nrfx 1.0.0 and 1.1.0 releases and has some fixes/updates (for example APPROTECT register set)

**Comment by plaes** [comment]
Ugh, apparently correct capitalization is `read-writeOnce`.

**Comment by Dirbaio** [comment]
there's no way to enforce the "write once" part, i'd just treat it as readwrite. PRs welcome.
